// Single Phase String Inverter(LV)
export interface Variant1 {
    id?: number,
    max_dc_input_power?: string,
    max_dc_input_voltage?: string,
    start_up_dc_input_voltage?: string,
    mppt_operating_range?: string,
    max_dc_input_current?: string,
    max_short_circuit_current?: string,
    no_of_mpp_trackers?: string,
    no_of_strings_per_mpp_tracker?: string,
    rated_output_power?: string,
    max_active_power?: string,
    rated_output_voltage_range?: string,
    rated_grid_frequency?: string,
    operating_phase?: string,
    rated_ac_grid_output_current?: string,
    max_ac_output_current?: string,
    output_power_factor?: string,
    total_harmonics_current_distortion?: string,
    dc_injection_current?: string,
    grid_frequency_range?: string,
    max_efficiency?: string,
    euro_efficiency?: string,
    mppt_efficiency?: string,
    dc_reverse_polarity_protection?: string,
    ac_short_circuit_protection?: string,
    ac_output_overcurrent_protection?: string,
    output_overvoltage_protection?: string,
    insulation_resistance_protection?: string,
    ground_fault_monitoring?: string,
    islanding_protection?: string,
    temparature_protection?: string,
    integrated_dc_switch?: string,
    remote_software_upload?: string,
    remote_change_of_operating_parameters?: string,
    surge_protection?: string,
    cabinate_size?: string,
    weight?: string,
    topology?: string,
    internal_consumption?: string,
    running_temparature?: string,
    ingress_protection?: string,
    noise_emission?: string,
    cooling_concept?: string,
    permissible_altitude?: string,
    wrranty?: string,
    grid_connection_standard?: string,
    operating_surroundings_humidity?: string,
    safety_emc_standard?: string,
    designed_ifetime?: string,
    display?: string,
    interface?: string,
}

// Three Phase String Inverter
export interface Variant2 {
    id?: number,
    max_dc_input_power?: string,
    max_dc_input_voltage?: string,
    start_up_dc_input_voltage?: string,
    mppt_operating_range?: string,
    max_dc_input_current?: string,
    max_short_circuit_current?: string,
    no_of_mpp_trackers?: string,
    no_of_strings_per_mpp_tracker?: string,
    rated_output_power?: string,
    max_active_power?: string,
    rated_output_voltage_range?: string,
    rated_grid_frequency?: string,
    operating_phase?: string,
    rated_ac_grid_output_current?: string,
    max_ac_output_current?: string,
    output_power_factor?: string,
    total_harmonics_current_distortion?: string,
    dc_injection_current?: string,
    grid_frequency_range?: string,
    max_efficiency?: string,
    euro_efficiency?: string,
    mppt_efficiency?: string,
    dc_reverse_polarity_protection?: string,
    ac_short_circuit_protection?: string,
    ac_output_overcurrent_protection?: string,
    output_overvoltage_protection?: string,
    insulation_resistance_protection?: string,
    ground_fault_monitoring?: string,
    islanding_protection?: string,
    temparature_protection?: string,
    integrated_dc_switch?: string,
    remote_software_upload?: string,
    remote_change_of_operating_parameters?: string,
    surge_protection?: string,
    cabinate_size?: string,
    weight?: string,
    topology?: string,
    internal_consumption?: string,
    running_temparature?: string,
    ingress_protection?: string,
    noise_emission?: string,
    cooling_concept?: string,
    permissible_altitude?: string,
    wrranty?: string,
    grid_connection_standard?: string,
    operating_surroundings_humidity?: string,
    safety_emc_standard?: string,
    designed_ifetime?: string,
    display?: string,
    interface?: string,
    
}

// Three Phase String Inverter(LV)

export interface Variant3 {
    id?: number,
    max_dc_input_power?: string,
    max_dc_input_voltage?: string,
    start_up_dc_input_voltage?: string,
    mppt_operating_range?: string,
    max_dc_input_current?: string,
    max_short_circuit_current?: string,
    no_of_mpp_trackers?: string,
    no_of_strings_per_mpp_tracker?: string,
    rated_output_power?: string,
    max_active_power?: string,
    rated_output_voltage_range?: string,
    rated_grid_frequency?: string,
    operating_phase?: string,
    rated_ac_grid_output_current?: string,
    max_ac_output_current?: string,
    output_power_factor?: string,
    total_harmonics_current_distortion?: string,
    dc_injection_current?: string,
    grid_frequency_range?: string,
    nominal_output_voltage_range?: string,
    max_efficiency?: string,
    euro_efficiency?: string,
    mppt_efficiency?: string,
    dc_reverse_polarity_protection?: string,
    ac_short_circuit_protection?: string,
    ac_output_overcurrent_protection?: string,
    output_overvoltage_protection?: string,
    insulation_resistance_protection?: string,
    ground_fault_monitoring?: string,
    islanding_protection?: string,
    temparature_protection?: string,
    integrated_dc_switch?: string,
    remote_software_upload?: string,
    remote_change_of_operating_parameters?: string,
    surge_protection?: string,
    cabinate_size?: string,
    weight?: string,
    topology?: string,
    internal_consumption?: string,
    running_temparature?: string,
    ingress_protection?: string,
    noise_emission?: string,
    cooling_concept?: string,
    permissible_altitude?: string,
    warranty?: string,
    grid_connection_standard?: string,
    operating_surroundings_humidity?: string,
    safety_emc_standard?: string,
    designed_lifetime?: string,
    display?: string,
    interface?: string,
    
}

// Hybrid Inverters

export interface Variant4 {
    id?: number,
    battery_type?: string,
    battery_voltage_range?: string,
    max_charging_current?: string,
    max_discharging_current?: string,
    charging_curve?: string,
    external_temperature_sensor?: string,
    charging_strategy_for_li_ion?: string,
    number_of_battery_input?: string,
    maxdc_input_power?: string,
    rated_pv_input_voltage?: string,
    start_up_voltage?: string,
    mppt_voltage_range?: string,
    full_load_dc_voltage_range?: string,
    pv_input_current?: string,
    max_pv_isc?: string,
    no_of_mppt_trackers?: string,
    no_of_strings_per_mppt_tracker?: string,
    rated_ac_output_and_ups_power?: string,
    max_ac_output_active_power?: string,
    ac_output_rated_current?: string,
    max_ac_output_current?: string,
    max_continuous_ac_passthrough?: string,
    peak_power?: string,
    power_factor_adjustment_range?: string,
    power_factor?: string,
    output_frequency_and_voltage?: string,
    grid_type?: string,
    total_harmonics_current_distortion?: string,
    dc_current_injection?: string,
    max_efficiency?: string,
    euro_efficiency?: string,
    mppt_efficiency?: string,
    integrated?: string, 
    over_voltage_category?: string,
    operating_temperature_range_cooling?: string,
    noise?: string,
    communication_with_bms?: string,
    installation_style?: string,
    warranty?: string,
    weight?: string,
    cabinet_size?: string,
    protection_degree?: string,
    grid_regulation?: string,
    safety_emc_standard?: string,
    max_dc_input_voltage?: string,
    rated_dc_input_voltage?: string,
    mppt_range?: string,
    rated_ac_output_active_power?: string,
    max_three_phase_unbalanced_output_current?: string,
    max_output_short_circuit_current?: string,
    generator_input_smart_load_ac_couple_current?: string,
    Surge_protection?: string,
}

//Accessory & Monitoring
export interface Variant5 {
    id?: number,
    energy_meter?: string,
    max_direct_current_measurement?: string,
    direct_voltage_measurement_between_phases?: string,
    direct_measurement_between_phase_and_neutral?: string,
    active_power?: string,
    reactive_power?: string,
    power_supply?: string,
    power_consumption?: string,
    ac_power_supply_input_voltage?: string,
    ac_power_supply_input_frequency ?: string, 
    dimenstion_in_mm ?: string,
    weight ?: string,
    mounting_options?: string,
    degree_of_protection?: string,
    display?: string,
    communication_interface?: string,
    max_number_of_devices_to_connect?: string,
    regulated_working_temperature_range?: string,
    humidity?: string,
    warranty?: string,
    remote_communication_interface?: string,
    working_frequency?: string,
    satellite_positioning?: string,
    antenna?: string,
    data_interface?: string,
    working_voltage?: string,
    working_power?: string,
    sim_card?: string,
    memory?: string,
    working_temperature?: string,
    working_humidity?: string,
    no_of_connections?: string,
    serial_communication_rate?: string,
    data_acquisition_interval?: string,
    user_configuration?: string,
    firmware_upgrade?: string,
    others?: string,
    
}

//Eternal Shine Series
export interface Variant6 { 
    id?: number,
    peak_power_pmax?: string,
    maximum_voltage_vmpp?: string,
    maximum_current_impp?: string,
    open_circuit_voltage_voc?: string,
    short_circuit_current_isc?: string,
    module_efficiency?: string,
    pmax_noct?: string,
    container?: string,
    pallets_container?: string,
    pieces_container?: string,
    tc_of_open_circuit_voltage?: string,
    tc_of_short_circuit_current?: string,
    t_of_power?: string,
    maximum_system_voltage?: string,
    noct?: string,
    temperature_range?: string,
    length?: string,
    width?: string,
    height?: string,
    weight?: string,
    junction_box?: string,
    cable_and_connections?: string,
    application_class?: string,
    superstrate?: string,
    cells?: string,
    encapsulation?: string,
    substrate?: string,
    frame?: string,
    design_machanical_load?: string,
    safety_factor_for_machanical_load?: string,
    maximum_series_fuse_rating?: string,
}

//ELAN SHINE  Series
export interface Variant7 {
    id?: number, 
    bifaciality_gain?: string,
    peak_power_pmax?: string,
    maximum_voltage_vmpp?: string,
    maximum_current_impp?: string,
    open_circuit_voltage_voc?: string,
    short_circuit_current_isc?: string,
    module_efficiency?: string,
    pmax_noct?: string,
    container?: string,
    pallets_container?: string,
    pieces_container?: string,
    tc_of_open_circuit_voltage?: string,
    tc_of_short_circuit_current?: string,
    t_of_power?: string,
    maximum_system_voltage?: string,
    noct?: string,
    temperature_range?: string,
    length?: string,
    width?: string,
    height?: string,
    weight?: string,
    junction_box?: string,
    cable_and_connections?: string,
    application_class?: string,
    superstrate?: string,
    cells?: string,
    encapsulation?: string,
    substrate?: string,
    frame?: string,
    design_machanical_load?: string,
    safety_factor_for_machanical_load?: string,
    maximum_series_fuse_rating?: string,
}

//BOS kit
export interface Variant8 {
    id?: number, 
    ip_rating?: string, 
    box_make?: string,
    capacity?: string,
    color?: string,
    box_size?: string,
    number_of_strings?: string,
    uv_protected?: string,
    voltage?: string,
    body_material?: string,
}



// variant model
export interface Variant {
    id?: number,
    category: string,
    Body_Text: string,
    selectedDate:string,
    // Body_Text: number,
    cate_id: number,
    varnt_order: number,
    specs: string,
    active_status: string;
}
